development: &base
  SESSION_SECRET: xxx
  DATABASE_URL: 'postgres://localhost/alpinist_development'
  ASSETS_SERVER_URL: "http://localhost:1234"
test:
  <<: *base
  DATABASE_URL: 'postgres://localhost/alpinist_test'
